
INGESTED_USERS_PATH = "data/ingested_users.csv"
INGESTED_PAYMENTS_PATH = "data/ingested_subscriptions.csv"
INGESTED_PLAYLISTS_PATH = "data/ingested_playlists.csv"
INGESTED_SONGS_PATH = "data/ingested_songs.csv"
INGESTED_ARTISTS_PATH = "data/ingested_artists.csv"
INGESTED_ALBUMS_PATH = "data/ingested_albums.csv"
INGESTED_PLAYS_PATH = "data/ingested_plays.csv"
INGESTED_FOLLOWERS_PATH = "data/ingested_followers.csv"

USERS_PATH="data/users.csv"
PAYMENTS_PATH="data/payments.csv"
PLAYLISTS_PATH="data/playlists.csv"
SONGS_PATH="data/songs.csv"
ARTISTS_PATH="data/artists.csv"
ALBUMS_PATH="data/albums.csv"
PLAYS_PATH="data/plays.csv"
FOLLOWERS_PATH="data/followers.csv"

SUBSCRIPTIONS_PATH = "data/subscriptions.csv"
TOP_SONGS_PATH = "data/top_songs.csv"
TRENDING_ARTISTS_PATH = "data/trending_artists.csv"
RECCOMENDED_SONGS_PATH = "data/recommended_songs.csv"
BEST_FRIENDS_PATH = "data/best_friends.csv"